### PR TITLE
frontend, backend: only show edit, delete dashboard when authenticated

### LINKED ISSUE #96: Meerkat Home allows clicking Edit, Delete etc. buttons even when unauthenticated
This is because the authentication challenge only occurs when the client actually hits the server, when saving or deleting a dashboard.

### PR DESCRIPTION
**Pull request by ollytom**
This works by first testing if authentication is configured on the server.
If so, authenticating to the server results in a cookie being returned.
The presence of a cookie changes how the dashboard list is rendered.

Cookies are generated by the server by creating "tokens": base64-encoded random bytes.
Tokens are only held in-process in memory.

I don't know how to create a "log in" button to prompt authentication
A <button> element which has its onClick attribute set to
meerkat.authenticate() may do the trick.

Closes #96

### CODE REVIEW

**Comment by davekempe** [comment]
This is going to be hard for me to test for correct function without a frontend component to go with. Perhaps @afoster can help out with adding something to this PR. I know @sol1-matt is keen to see this work correctly.

**Comment by sol1-matt** [comment]
Looking at the code this looks like it replaces the existing dashboard listing with a view only listing if auth is configured locally and no cookie is set.

So if we spin up a instance of this and add auth to the config locally then I'm assuming we have this working for view. I'm less clear on how you login to become authorized.

Is there this solution can be used with an external auth source? 
Can the cookie or auth param's be passed in with the request?

**Comment by ollytom** [comment]
> This is going to be hard for me to test for correct function without a frontend component to go with.

Yep totally. I actually did get a basic “Log in” button, but I got out of my depth with the react component stuff.
In particular I didn’t really understand how to trigger state changes between components. I could have made the Home component way bigger, but I figured better to just to publish this patch and get people talking and fiddling would be more productive! :)

Here’s meerkat running with the latest auth patch: http://45.77.51.37:8585/
To trigger an authentication prompt, try creating a dashboard.
Credentials are the same as in the example configuration file.

Give it a go!

**Review by davekempe — APPROVED** [review]
looks good to me!

**Pull request merged**
