### PR TITLE
Add a digital clock

### PR DESCRIPTION
**Pull request by ollytom**
See commit message for description

### CODE REVIEW

**Comment by ollytom** [comment]
A couple of things that may be required, off the top of my head:

* fixed width font for the time. Otherwise the numbers "move around" as the time changes.
* 24-hour time format seems safer for the environments meerkat will run in

**Comment by ollytom** [comment]
>     * fixed width font for the time. Otherwise the numbers "move around" as the time changes.
>     * 24-hour time format seems safer for the environments meerkat will run in

Updated patch with these set

**Comment by davekempe** [comment]
I will need to try this out with both fixed width and 24 hr time to see how it looks first

**Comment by davekempe** [comment]
The current fixed width font looks a little weird with the dots in the middle of the zeros:
https://clock.demo.meerkat.run/view/clock-test
Can I suggest we use sans serif and font-variant-numeric: tabular-nums; as outlined here:
https://stackoverflow.com/questions/4686754/making-every-character-on-a-web-page-the-same-width

**Comment by ollytom** [comment]
> The current fixed width font looks a little weird with the dots in the middle of the zeros

Depends on the font face that the browser and OS choose for
"monospace" but yeah there's a chance that it will look a bit off.

> Can I suggest we use sans serif and font-variant-numeric: tabular-nums; as outlined here:

Wow that's really cool I never saw that before. Nice find! Updated
with this property set and looks like it works well!

I've also updated the patch to use the standard `<time>` element
rather than `<p>` for paragraph.

**Review by davekempe — APPROVED** [review]
This works well enough on my test machine, i'm ok to merge

**Pull request merged**
