### PR TITLE
Feature/world clock

### PR DESCRIPTION
**Pull request by n2lose**
@davekempe : please help me to review this pull request

### CODE REVIEW

**Comment by ollytom** [comment]
Thanks a lot for this! Is there a way to enumerate timezones from the browser?
Then we don’t have to import the timezones.json file.

**Comment by n2lose** [comment]
> Thanks a lot for this! Is there a way to enumerate timezones from the browser? Then we don’t have to import the timezones.json file.
No, the browsers just have their timezone in its self. So, I have to import the timezones.json to get most of timezones on the world.

**Comment by davekempe** [comment]
The only other issue will be maintaining daylight saving I spose. Not sure exactly how to do that. Could get all complicated,. But I do see customers wanting daylight saving support.

**Comment by ollytom** [comment]
> No, the browsers just have their timezone in its self.

I did some research and this doesn’t seem to be the case.
In Firefox 103.0 on macOS 12.4:

	Intl.supportedValuesOf(‘timeZone’).length;

I get 468 timezones. Same on OpenBSD 7.1.
In Safari in macOS and Chromium on OpenBSD I get 428.

It looks like we can specify a timezone via the `toLocaleString` method 
of `Date` 
(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString).
This prints the current time in Ghana and Mongolia:

	console.log(new Date().toLocaleString(‘en-US’, { timeZone: 
‘Africa/Accra’ });
	console.log(new Date().toLocaleString(‘en-US’, { timeZone: 
‘Asia/Ulaanbaatar’ });

What do you think about reworking the change to use the built-in 
timezones instead?

**Comment by ollytom** [comment]
> No, the browsers just have their timezone in its self.

I did some research and this doesn’t seem to be the case.
In Firefox 103.0 on macOS 12.4:

```
Intl.supportedValuesOf(‘timeZone’).length;
```

I get 468 timezones. Same on OpenBSD 7.1.
In Safari in macOS and Chromium on OpenBSD I get 428.

It looks like we can specify a timezone via the `toLocaleString` method
of `Date`
(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString).
This prints the current time in Ghana and Mongolia:

```
console.log(new Date().toLocaleString(‘en-US’, { timeZone: ‘Africa/Accra’ });
console.log(new Date().toLocaleString(‘en-US’, { timeZone: ‘Asia/Ulaanbaatar’ });
```

What do you think about reworking the change to use the built-in timezones instead?

**Comment by davekempe** [comment]
@ollytom will this give us timezone aware daylight saving maintenance too? They change more than they should.

**Comment by ollytom** [comment]
> @ollytom will this give us timezone aware daylight saving maintenance 
> too? They change more than they should.

That's a good question! This might be fun to work out...
Looking at 
https://en.wikipedia.org/wiki/Daylight_saving_time_by_country,
I can see that right now in the USA, Arizona is in Daylight Savings 
Time,
but states north of it, say, Colorado, are not.
This means two places are in the same time zone but one observes DST, 
the other not.
Arizona is now in "Mountain Standard Time" and Colorado is in "Mountain 
Daylight Time".
If the browser supports daylight savings then it should know time in 
those two places is different.

So to check the time in Arizona:

	console.log(new Date().toLocaleString('en-US', { timeZone: 
'America/Phoenix' }));
	"7/30/2022, 10:33:20 PM"

And in Denver, Colorado:

	console.log(new Date().toLocaleString('en-US', { timeZone: 
'America/Denver' }));
	"7/30/2022, 11:33:20 PM"

Looks like the answer is yes it is supported!

**Comment by n2lose** [comment]
> What do you think about reworking the change to use the built-in timezones instead?
@ollytom : I will update to use the built-in timezones on browsers, but just to be informed as you mentioned, there is a different between the timezone list on -moz (Mozilla Firefox ) and -webkit (Chrome, Edge)

@davekempe : I will check to see if their browsers support Daylight saving time in the built-in Date object and implement it

**Comment by davekempe** [comment]
OK I had a chance to test it out. Seems to be working well, however it does need to be moveable. When I add the digitalClock Element, it is fixed in place. It needs to be able to be moved like the Icinga Card and other elements.
There also seems to be a lot of extraneous code in this Element from copying the Icinga Card element. Please clean it up a bit so the code reflects a little more all it needs to do, as opposed to lots of extra functions. This Clock element is just for displaying the time, and has no interaction or scope for pulling data from Icinga or the backend api at all.

**Comment by n2lose** [comment]
> OK I had a chance to test it out. Seems to be working well, however it does need to be moveable. When I add the digitalClock Element, it is fixed in place. It needs to be able to be moved like the Icinga Card and other elements. There also seems to be a lot of extraneous code in this Element from copying the Icinga Card element. Please clean it up a bit so the code reflects a little more all it needs to do, as opposed to lots of extra functions. This Clock element is just for displaying the time, and has no interaction or scope for pulling data from Icinga or the backend api at all.

@davekempe: I have cleaned up and remove some redundant code, feel free to check it!

**Comment by davekempe** [comment]
Code looks much cleaner now, I tried it out. I still can't move the clock around the page. I don't know preact enough to be able to say how to fix this, but if you build it and use it, you can see that the Icinga Card Element can be moved around the page. This digitalClock cannot. Can you fix that please? It is important the clock can be moved to where the users want it to be, with respect to the background image.

**Comment by afoster** [comment]
Please also remove timezones.json if not in use.

**Comment by davekempe** [comment]
ooh I got it to move - if you make the element really big, you can drag it around. and then resize it. Not sure why.

**Comment by n2lose** [comment]
> ooh I got it to move - if you make the element really big, you can drag it around. and then resize it. Not sure why.

yeah! As I'm debugging, When it's small the element that handleMove event is :
image

Correct one should be: 
image

**Comment by n2lose** [comment]
@davekempe : Please pull the latest and check again! I have just pushed a fix for move it.

**Comment by afoster** [comment]
I think it needs `pointer-events: none` on the `.digital-clock` class to make dragging behaviour consistent with other types of elements.

**Comment by n2lose** [comment]
> I think it needs `pointer-events: none` on the `.digital-clock` class to make dragging behaviour consistent with other types of elements.

I have fixed it.

**Comment by davekempe** [comment]
Tested this and its working well now.

**Comment by davekempe** [comment]
hey @n2lose sorry this failed to build. Not sure exactly how to work with these eslint plugins, but it worked OK when I installed it for me from scratch.

**Comment by ollytom** [comment]
Hey @n2lose this change is difficult to review. It contains almost 20 commits.
Are you able to rebase your changes to a single one? If you're unfamiliar with this procedure here's a guide I find useful: https://git-rebase.io/

**Comment by ollytom** [comment]
To make this easier, I've created a new PR, authorship still attributed to Lam. See https://github.com/meerkat-dashboard/meerkat/pull/111. Trust that's ok :)

**Pull request closed without merging**
